travis:
  secure:
    BINSTAR_TOKEN: WlfmhN3uFBrcqMXLcAzeuOKVKg+GsEMXmNF+mIscOaQu4AXdFLdnHpcLnHOWmdYjNckoi6n2yjiRsIFkKJGEiHIug45NyllomMPBxNMJKbrtYLwo2IMsQD5jJNq0dekNwzOxOQRo1haxxxXq3fUv1cHGWmQ3L6X0MzFV6Fh6OKlRxgZg1iqT02RS+y33rcysicJUeoKeQTYfYJ+r1IOC3IZsjrFpMyymdTHVSDTIr4KVWVJSZnfwQ3GlSLZQ+lkbmc/GZLIZPuIeiA5WWm0VC9lmfMTWZ98uRYm7QtcowA6932HxtqTnDX5Odvz0nY+ZnQkMmWkld0vKBzaOx+Nlaz/pzY8t9Xz6odFkHfCf9wxbiSADThj87ULx45DHxGAIBBhXzWef1zG22I6uFb6SzL+xVZAS1DjGeOJ32iAb5HPCpDoIFI77H3Iy3JT+os+xR7gLyvE4Ho7Qw9cCiDRCQjuS00NYiImmo480ZVRP6e94roYhxiQZnRRYWUb5YJlWITYyBcrdKCTlQMMyQrbZbo624VlxZQR90CTCxZ4noPT1SU6Ju6wP1QDbkdZUk/9qyZbE/xu0woOkvHWIs2vy9Vt809K3s3l7qfZjHl6xbH45AP6alGrgQH2FY3iV/HP2zT3VsQto49us9jIos4mUY/YEA6aPLUkD3+wlEY58ves=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
